// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMeHszz9MEXCYaz3ytUHwlkCrVTqapvLc',
    appId: '1:590737593890:web:362c0fbfd9041183909c7b',
    messagingSenderId: '590737593890',
    projectId: 'motocheck-ee3f5',
    authDomain: 'motocheck-ee3f5.firebaseapp.com',
    storageBucket: 'motocheck-ee3f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpMX5aewKgLDP0H7XoLmlONaFfH19H2yo',
    appId: '1:590737593890:android:df30530a02a20940909c7b',
    messagingSenderId: '590737593890',
    projectId: 'motocheck-ee3f5',
    storageBucket: 'motocheck-ee3f5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR1sBY68K-2y7Xv9vdZ73TckSjqzjyET4',
    appId: '1:590737593890:ios:9d54f7ca7a4ed095909c7b',
    messagingSenderId: '590737593890',
    projectId: 'motocheck-ee3f5',
    storageBucket: 'motocheck-ee3f5.firebasestorage.app',
    iosClientId: '590737593890-qe02ff2qq4cesoq9l84ehk3u633sb3d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.controlDeMototaxisOTaxis',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR1sBY68K-2y7Xv9vdZ73TckSjqzjyET4',
    appId: '1:590737593890:ios:9d54f7ca7a4ed095909c7b',
    messagingSenderId: '590737593890',
    projectId: 'motocheck-ee3f5',
    storageBucket: 'motocheck-ee3f5.firebasestorage.app',
    iosClientId: '590737593890-qe02ff2qq4cesoq9l84ehk3u633sb3d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.controlDeMototaxisOTaxis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMeHszz9MEXCYaz3ytUHwlkCrVTqapvLc',
    appId: '1:590737593890:web:d7463186cb2e1ffe909c7b',
    messagingSenderId: '590737593890',
    projectId: 'motocheck-ee3f5',
    authDomain: 'motocheck-ee3f5.firebaseapp.com',
    storageBucket: 'motocheck-ee3f5.firebasestorage.app',
  );
}
